/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.motemere.stringanalisercore;

public class App {

    public String getGreeting() {
        return "Hey! Shuba duba!!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
