/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.analiser.core;

public class App {

  /**
   * Returns a greeting to the caller.
   *
   * @return the greeting
   */
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
